/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogoVelha;

/**
 *
 * @author HP
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelX1 = new javax.swing.JLabel();
        jLabelX2 = new javax.swing.JLabel();
        jLabelX3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TelaDeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(619, 679));
        setMinimumSize(new java.awt.Dimension(619, 679));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Lucida Bright", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 204));
        jButton1.setText("Jogar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 490, 360, 80);

        jLabelX1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\imagens\\Jogador 1.png")); // NOI18N
        getContentPane().add(jLabelX1);
        jLabelX1.setBounds(130, 360, 90, 100);

        jLabelX2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\imagens\\Jogador 1.png")); // NOI18N
        getContentPane().add(jLabelX2);
        jLabelX2.setBounds(370, 110, 120, 110);

        jLabelX3.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\imagens\\Jogador 1.png")); // NOI18N
        getContentPane().add(jLabelX3);
        jLabelX3.setBounds(250, 240, 90, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\imagens\\Jogador 2 Fundo preto.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 130, 90, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\imagens\\Jogador 2 Fundo preto.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 370, 90, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\imagens\\Jogador 2 Fundo preto.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 250, 90, 80);

        TelaDeFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\imagens\\Tela de fundo Jogo da velha.png")); // NOI18N
        getContentPane().add(TelaDeFundo);
        TelaDeFundo.setBounds(-30, -60, 650, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        dispose();
        TelaDoJogo jogo = new TelaDoJogo();
        jogo.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setFont(new java.awt.Font("Lucida Bright", 0, 42));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setFont(new java.awt.Font("Lucida Bright", 0, 36));
    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelaDeFundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelX1;
    private javax.swing.JLabel jLabelX2;
    private javax.swing.JLabel jLabelX3;
    // End of variables declaration//GEN-END:variables
}
